version: "3.8"

services:
  minio:
    image: minio/minio
    container_name: minio
    ports:
      - "9000:9000"   
      - "9001:9001"   
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data

  mlflow:
    build:
      context: ./mlflow
      dockerfile: Dockerfile
    container_name: mlflow
    ports:
      - "5000:5000"
    depends_on:
      - minio
    environment:
      # Configuração para armazenar artefatos no MinIO (S3)
      MLFLOW_S3_ENDPOINT_URL: http://minio:9000
      AWS_ACCESS_KEY_ID: minioadmin
      AWS_SECRET_ACCESS_KEY: minioadmin
      AWS_DEFAULT_REGION: us-east-1
    command: mlflow server --host 0.0.0.0 --port 5000 --backend-store-uri postgresql://neondb_owner:npg_ZyDj34mdtqLu@ep-crimson-glitter-ac9d92fb-pooler.sa-east-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require --serve-artifacts --artifacts-destination s3://mlflow

        

  fastapi:
    build:
      context: ./fastapi
    container_name: fastapi-inmet
    ports:
      - "8000:8000"
    environment:
      MINIO_ENDPOINT: "minio:9000"
      MINIO_ACCESS_KEY: "minioadmin"
      MINIO_SECRET_KEY: "minioadmin"
      MINIO_BUCKET: "inmet-raw"
    depends_on:
      - minio
    volumes:
      - ./data:/data:ro

  thingsboard:
    image: thingsboard/tb-postgres
    container_name: thingsboard
    restart: always
    depends_on:
      - th-postgres
    environment:
      - TB_SETUP=true
      - SPRING_DATASOURCE_URL=jdbc:postgresql://th-postgres:5432/thingsboard
      - SPRING_DATASOURCE_USERNAME=thingsboard
      - SPRING_DATASOURCE_PASSWORD=thingsboard
    ports:
      - "8080:8080"
      - "1883:1883"
      - "5683:5683/udp"
    volumes:
      - tb-data:/data
      - tb-logs:/var/log/thingsboard

  th-postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: thingsboard
      POSTGRES_USER: thingsboard
      POSTGRES_PASSWORD: thingsboard
    volumes:
      - tb-postgres-data:/var/lib/postgresql/data

volumes:
  minio_data:
  tb-postgres-data:
  tb-data:
  tb-logs:
